apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bee-nodejs
  janus-idp.io/tekton: bee-nodejs
  backstage.io/kubernetes-id: bee-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bee-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
