apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bee-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bee-nodejs 
  name: bee-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bee-nodejs 
